version: "2"
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  db:
    image: mongo:4.4.2-bionic
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
  node_modules: